### ISSUE TITLE
Net::HTTP::Persistent::Error: too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 2 requests on 14759220 

### ISSUE THREAD

**Issue by bjoseph** [sparklemotion/mechanize#123]
I am trying to do some simple screen scraping on etrade's website but am getting a similar issue that was reported by someone earlier.  I read through that message thread but it doesn't look like it was ever resolved.  

Here is the error I am getting back:

```
Net::HTTP::Persistent::Error: too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 2 requests on 14759220
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/net-http-persistent-1.8/lib/net/http/persistent.rb:446:in `rescue in request'
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/net-http-persistent-1.8/lib/net/http/persistent.rb:422:in `request'
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/mechanize-2.0.1/lib/mechanize/http/agent.rb:204:in `fetch'
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/mechanize-2.0.1/lib/mechanize.rb:628:in `post_form'
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/mechanize-2.0.1/lib/mechanize.rb:520:in `submit'
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/mechanize-2.0.1/lib/mechanize/form.rb:167:in `submit'
    from (irb):74
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/railties-3.0.9/lib/rails/commands/console.rb:44:in `start'
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/railties-3.0.9/lib/rails/commands/console.rb:8:in `start'
    from /Users/benny/.rvm/gems/ruby-1.9.2-p180@taxhaven/gems/railties-3.0.9/lib/rails/commands.rb:23:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Here is my code:

```
require 'rubygems'
require 'mechanize'

agent = Mechanize.new
login_page = agent.get("https://www.etrade.com")
form = login_page.form_with(:action => '/login.fcc') 
form.USER     = "test"
form.PASSWORD = "test12"
form.submit
```

Any ideas?

Thanks

**Comment by Mifrill** [comment]
I get this error:
```
I, [2018-03-25 14:56:07 +0000#7230]  INFO -- : Scheduler: visiting = http://gebrauchtmaschinen-bodensee.de/seiten/maschinenblatt.php?artikel_ID=278, last_request = 1521989767
E, [2018-03-25 14:56:07 +0000#7230] ERROR -- : Scheduler: `Net::HTTP::Persistent::Error: too many connection resets (due to end of file reached - EOFError) after 8 requests on 70058197957180, last used 3.017852706 seconds ago`
/root/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill'
/root/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
/root/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/protocol.rb:167:in `readline'
/root/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http/response.rb:40:in `read_status_line'
/root/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http/response.rb:29:in `read_new'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.13.0/lib/seahorse/client/net_http/patches.rb:30:in `block in new_transport_request'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.13.0/lib/seahorse/client/net_http/patches.rb:27:in `catch'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.13.0/lib/seahorse/client/net_http/patches.rb:27:in `new_transport_request'
/root/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http.rb:1464:in `request'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:999:in `request'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:274:in `fetch'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-mechanize-1.5.0/lib/capybara/mechanize/browser.rb:115:in `process_remote_request'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-mechanize-1.5.0/lib/capybara/mechanize/browser.rb:43:in `block (2 levels) in <class:Browser>'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:69:in `process'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:41:in `process_and_follow_redirects'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:22:in `visit'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.17.0/lib/capybara/rack_test/driver.rb:44:in `visit'
/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.17.0/lib/capybara/session.rb:274:in `visit'
```
Еhis happens in a long process. The number of requests and url of error may vary.

```
I, [2018-03-26 04:55:47 +0000#16779]  INFO -- : Scheduler: visiting = http://gebrauchtmaschinen-bodensee.de/seiten/maschinenblatt.php?artikel_ID=280, last_request = 1522040147
E, [2018-03-26 04:55:48 +0000#16779] ERROR -- : Scheduler: `Net::HTTP::Persistent::Error: too many connection resets (due to end of file reached - EOFError) after 1 requests on 69821907747740, last used 2.998685685 seconds ago`
/root/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill'
/root/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
```
I tried different settings, including headers, but the error could not be fixed.
```
headers "Keep-Alive" => "timeout=5, max=150"

    { idle_timeout: 4,
      read_timeout: 40,
      ignore_bad_chunking: true,
      retry_change_requests: true }.each do |parameter, value|
      page.driver.browser.agent.send("#{parameter}=", value)
    end
```
any ideas? Thank you
