### ISSUE TITLE
JRuby compatibility

### ISSUE THREAD

**Issue by BanzaiMan** [sparklemotion/mechanize#209]
Starting with version 2.1, `mechanize` now relies on `domain_name,` which in turn depends on `unf` and `unf_ext`. The last gem, `unf_ext`, requires a C extension. Is there a way to avoid this?

**Comment by Fenhanwang** [comment]
using Mechanize 2.7.4 and already install unf 0.1.4 java.

**Comment by Fenhanwang** [comment]
using Mechanize 2.7.4 and already install unf 0.1.4 java.

**Comment by Fenhanwang** [comment]
using **Mechanize 2.7.4**, **JRuby 1.7.24**(also try JRuby 9k); already install **unf 0.1.4 java**.Then in Jirb
```Ruby
require 'mechanize'
a = Mechanize.new
a.get "http://jruby.org/"
```
The top of error stack is 
**NoMethodError: undefined method name' for nil:NilClass**
**from /home/f/.rvm/gems/ruby-2.2.1/gems/mechanize-2.7.4/lib/mechanize/util.rb:128:in detect_charset'**

I check the source code and looks like the the is a fix on the encoding issue for JRuby but feels like there is still a bug

**Comment by PizzaPill** [comment]
This seems fixed in the current master, see https://github.com/sparklemotion/mechanize/commit/0e827f296ff29e6b35ed700a47694aea0a57a561#diff-464ac65e6c7db20876496dcda72995ba

**Comment by Fenhanwang** [comment]
@PizzaPill  right. At first time, I thought it was fixed

**Comment by jimjames99** [comment]
Me too. Need to bump the gem version to include the patch. Can you bump the gem version please?
````
jruby-9.0.5.0 :002 > a = Mechanize.new
 => #<Mechanize:0x6f0cb5a1 @html_parser=Nokogiri::HTML, @history_added=nil, @proxy_port=nil, @default_encoding=nil, @force_default_encoding=false, @keep_alive_time=0, @pluggable_parser=#<Mechanize::PluggableParser:0x1b29d52b @default=Mechanize::File, @parsers={"text/html"=>Mechanize::Page, "application/xhtml+xml"=>Mechanize::Page, "application/vnd.wap.xhtml+xml"=>Mechanize::Page, "image"=>Mechanize::Image, "text/xml"=>Mechanize::XmlFile, "application/xml"=>Mechanize::XmlFile}>, @agent=#<Mechanize::HTTP::Agent:0x655523dd @ignore_bad_chunking=false, @cookie_jar=#<Mechanize::CookieJar:0x6f7e336b @store=#<HTTP::CookieJar::HashStore:0x3a2b2322 @jar={}, @logger=nil, @gc_threshold=150, @gc_index=0, @mon_mutex=#<Mutex:0x5e1218b4>, @mon_owner=nil, @mon_count=0>>, @redirect_ok=true, @keep_alive=true, @digest_auth=#<Net::HTTP::DigestAuth:0x12958360 @nonce_count=-1, @mon_mutex=#<Mutex:0xc6e0f32>, @mon_owner=nil, @mon_count=0>, @follow_meta_refresh_self=false, @authenticate_methods={}, @max_file_buffer=100000, @follow_meta_refresh=false, @digest_challenges={}, @open_timeout=nil, @content_encoding_hooks=[], @read_timeout=nil, @history=[], @webrobots=nil, @robots=false, @user_agent="Mechanize/2.7.4 Ruby/2.2.3p0 (http://github.com/sparklemotion/mechanize/)", @pass=nil, @pre_connect_hooks=[], @context=#<Mechanize:0x6f0cb5a1 ...>, @conditional_requests=true, @request_headers={}, @post_connect_hooks=[], @auth_store=#<Mechanize::HTTP::AuthStore:0x6f3f0fae @default_auth=nil, @auth_accounts={}>, @redirection_limit=20, @authenticate_parser=#<Mechanize::HTTP::WWWAuthenticateParser:0x21a66d45 @scanner=nil>, @gzip_enabled=true, @http=#<Net::HTTP::Persistent:0x1f966492 @retry_change_requests=false, @reuse_ssl_sessions=true, @keep_alive=300, @ssl_generation=1, @verify_callback=nil, @override_headers={}, @max_requests=nil, @private_key=nil, @request_key=:net_http_persistent_mechanize_requests, @cert_store=nil, @idle_timeout=5, @proxy_uri=nil, @open_timeout=nil, @no_proxy=[], @read_timeout=nil, @certificate=nil, @ssl_version=nil, @ssl_generation_key=:net_http_persistent_mechanize_ssl_generations, @timeout_key=:net_http_persistent_mechanize_timeouts, @retried_on_ruby_2=true, @generation_key=:net_http_persistent_mechanize_generations, @verify_mode=1, @http_versions={}, @name="mechanize", @debug_output=nil, @headers={}, @socket_options=[[6, 1, 1]], @ca_file=nil, @ruby_1=false, @generation=1>, @allowed_error_codes=[], @scheme_handlers={"http"=>#<Proc:0x4a68135e@/Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:174 (lambda)>, "https"=>#<Proc:0x4a68135e@/Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:174 (lambda)>, "relative"=>#<Proc:0x4a68135e@/Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:174 (lambda)>, "file"=>#<Proc:0x4a68135e@/Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:174 (lambda)>}>, @log=nil, @proxy_addr=nil, @watch_for_set=nil, @proxy_user=nil, @proxy_pass=nil>
jruby-9.0.5.0 :003 > a.get "http://jruby.org/"
NoMethodError: undefined method `name' for nil:NilClass
	from /Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize/util.rb:128:in `detect_charset'
	from /Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize/page.rb:38:in `initialize'
	from /Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize.rb:1259:in `parse'
	from /Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:897:in `response_parse'
	from /Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:288:in `fetch'
	from /Users/jjames/.rvm/gems/jruby-9.0.5.0/gems/mechanize-2.7.4/lib/mechanize.rb:464:in `get'
	from (irb):3:in `<eval>'
	from org/jruby/RubyKernel.java:976:in `eval'
	from org/jruby/RubyKernel.java:1287:in `loop'
	from org/jruby/RubyKernel.java:1096:in `catch'
	from org/jruby/RubyKernel.java:1096:in `catch'
	from /Users/jjames/.rvm/rubies/jruby-9.0.5.0/bin/irb:13:in `<top>'

jruby-9.0.5.0 :005 > Mechanize::VERSION
 => "2.7.4"
````
