### ISSUE TITLE
error: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure

### ISSUE THREAD

**Issue by muppanenimanasa** [sparklemotion/mechanize#424]
Please share what is the root cause of this issue,most of the blogs are telling, this is  an issue with OpenSSL verion.

**Comment by rilut** [comment]
I'm experiencing this too now. I had downloaded `cacert.pem` and added it to the path as instructed in https://gist.github.com/fnichol/867550 , it doesn't work for me

```ruby
require "mechanize"
URL= 'https://google.com'
m = Mechanize.new
page=m.get URL
page=m.get URL
# https://google.com is used as an example because not all sites would throw an error. https://example.com would be just fine.
# A site that I was scraping on throws the same error as Google do
```

Pasting the above code into irb would resulting in the 4th line throwing an error, and the 5th line works just fine

```
irb(main):004:0> page=m.get URL
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `connect'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `connect'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:858:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:259:in `fetch'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
        from (irb):4
        from C:/RailsInstaller/Ruby2.1.0/bin/irb:11:in `<main>'
irb(main):005:0> page=m.get URL
=> #<Mechanize::Page
 {url
  #<URI::HTTPS:0x42077d0 URL:https://www.google.co.id/?gws_rd=cr&ei=2UImVZ_4Oce2uATn1oC4DQ>}
 {meta_refresh}
 {title "Google"}
 {iframes}
 {frames}
 {links
  #<Mechanize::Page::Link
```
I'm on Windows 10 TP x64, RailsInstaller 3.1.0 (`ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]`), mechanize 2.7.3
