### ISSUE TITLE
way to set limit to avoid Faraday::RedirectLimitReached ?

### ISSUE THREAD

**Issue by chrisallick** [sparklemotion/mechanize#467]
Hello,
I was running into erro

```
2016-03-13 17:39:29 - MetaInspector::RequestError - too many redirects; last one to: http://www.nytimes.com/2016/03/13/upshot/the-geography-of-trumpism.html?smid=tw-upshotnyt&smtyp=cur&_r=0:
    /Users/callick/.rvm/gems/ruby-2.2.1/gems/metainspector-5.1.0/lib/meta_inspector/request.rb:44:in `rescue in response'
    /Users/callick/.rvm/gems/ruby-2.2.1/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:80:in `block in perform_with_redirection': too many redirects; last one to: http://www.nytimes.com/2016/03/13/upshot/the-geography-of-trumpism.html?smid=tw-upshotnyt&smtyp=cur&_r=0 (FaradayMiddleware::RedirectLimitReached)
```

And am using

```
                    begin
                      page = MetaInspector.new(url.expanded_url, faraday_options: { ssl: { verify: false } })
                    rescue Faraday::RedirectLimitReached
                    else
                        if page.meta['description']
                            tweet_obj = { :text => page.meta['description'], :name => t_name, :type => "meta" }
                            tweets.push( tweet_obj )
                        elsif page.meta['og:description']
                            tweet_obj = { :text => page.meta['og:description'], :name => t_name, :type => "meta" }
                            tweets.push( tweet_obj )
                        end
                    end
```

as a work around, but it would be nice to simply set a redirect limit.

**Comment by leejarvis** [comment]
Sorry but I don't see how this is related to Mechanise
