### ISSUE TITLE
upgrade net-http-persistent dependency

### ISSUE THREAD

**Issue by maia** [sparklemotion/mechanize#491]
Would it be possible to upgrade the `net-http-persistent` dependency to `"~> 3.0"` for Ruby 2.x versions? It has been released in October 2016, and it would allow to upgrade other gems which do not accept a 2.x version anymore.
```
if RUBY_VERSION >= "2.0"
  spec.add_runtime_dependency "net-http-persistent",  [ "~> 3.0" ]
else
  spec.add_runtime_dependency "net-http-persistent",  [ ">= 2.5.2", "~> 2.5" ]
end
```
Thanks!

**Comment by maia** [comment]
@knu Please excuse the request, but is there anything blocking the upgrade of the `net-http-persistent` dependency? Thanks.

**Comment by maia** [comment]
@knu, @olleolleolle, any chances of updating the `net-http-persistent` dependency? Thanks!

**Comment by knu** [comment]
@maia Looks like upgrading net-http-persistent to 3.0 would require some change.  Also, I don't see why we should restrict the dependency for ruby >= 2.0 to net-http-persistent ~> 3.0.  It's been working fine with 2.x on ruby >=2.0.

**Comment by maia** [comment]
@knu I have no objections to keeping loose requirements. My specific interest is to be able to run current versions of mechanize together with current versions of [link_thumbnailer](https://github.com/gottfrois/link_thumbnailer), which has updated their net-http-persistency to ~> 3.0 in gottfrois/link_thumbnailer@286c685e27db168ad69bcdf1d33ef1f6b0de8587 - I'm unsure why the constraint on their side was introduced, maybe @gottfrois or @jkeam can chime in?

**Comment by weshatheleopard** [comment]
I'm getting errors after this upgrade:
```
        8: from /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/2.5.0/bundler/gems/mechanize-b499a8380511/lib/mechanize/page/link.rb:30:in `click'
        7: from /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/2.5.0/bundler/gems/mechanize-b499a8380511/lib/mechanize.rb:348:in `click'
        6: from /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/2.5.0/bundler/gems/mechanize-b499a8380511/lib/mechanize.rb:464:in `get'
        5: from /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/2.5.0/bundler/gems/mechanize-b499a8380511/lib/mechanize/http/agent.rb:280:in `fetch'
        4: from /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:927:in `request'
        3: from /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:642:in `connection_for'
        2: from /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:642:in `ensure in connection_for'
        1: from /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent/pool.rb:16:in `checkin'
ConnectionPool::Error (no connections are checked out)
```
