### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by brauliobo** [sparklemotion/mechanize#498]
```
#<RuntimeError: can't add a new key into hash during iteration>
[2] pry(main)> e.backtrace
=> ["/home/braulio/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mechanize-2.7.5/lib/mechanize/history.rb:28:in `push'",
 "/home/braulio/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:1332:in `add_to_history'",
 "/home/braulio/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:465:in `get'",
```

**Comment by leejarvis** [comment]
Thanks, do you have any steps to reproduce?

**Comment by brauliobo** [comment]
Nop, it should be fixed by making it thread safe

**Comment by leejarvis** [comment]
@brauliobo perhaps you're right, but I can't reproduce your error even with a multi-threaded program, so some help would be really appreciated

**Comment by brauliobo** [comment]
When running 400k scraping tasks I got 211 ocurrences of this, so it seems it is hard to reproduce

**Comment by flavorjones** [comment]
I also cannot reproduce this, so closing until/unless we have more information. Thanks.
