### ISSUE TITLE
Roll back net-http-persistent to 2.9.4?

### ISSUE THREAD

**Issue by andymeneely** [sparklemotion/mechanize#529]
I recently had mechanize regress for me and got this error on a file that had `require 'mechanize'`:

```
>ruby trymech.rb
Traceback (most recent call last):
        8: from trymech.rb:1:in `<main>'
        7: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        6: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        5: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mechanize-2.7.6/lib/mechanize.rb:6:in `<top (required)>'
        3: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        2: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:190:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:205:in `<class:Persistent>': uninitialized constant Process::RLIMIT_NOFILE (NameError)
```

The way I fixed it was:
```
> gem uninstall net-http-persistent

You have requested to uninstall the gem:
        net-http-persistent-3.0.0

mechanize-2.7.6 depends on net-http-persistent (>= 2.5.2)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled net-http-persistent-3.0.0

>gem install net-http-persistent -v 2.9.4
Fetching: net-http-persistent-2.9.4.gem (100%)
Successfully installed net-http-persistent-2.9.4
Parsing documentation for net-http-persistent-2.9.4
Installing ri documentation for net-http-persistent-2.9.4
Done installing documentation for net-http-persistent after 1 seconds
1 gem installed

>ruby trymech.rb
```
(success!)

Looking at the net-http-persistent issue - looks like a [dead gem that others are proposing abandoning](https://github.com/drbrain/net-http-persistent/issues/79). Should mechanize cap the version? Or use something different?

**Comment by philiprasannakumar** [comment]
Thanks a lot @andymeneely

**Comment by benforeva** [comment]
This worked for me :+1:

**Comment by monkeysuffrage** [comment]
Me too

**Comment by pestovpvl** [comment]
Thank you! It is works!

**Comment by ShaunGrey** [comment]
worked for me

**Comment by flavorjones** [comment]
Closing, `net-http-persistent` is a supported gem with recent releases.

**Comment by andymeneely** [comment]
Hooray! There are many students who use this for an assignment that will be happy.
