### ISSUE TITLE
ruby-head test failures related to the HTTP::Cookie API

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/mechanize#637]
Currently ruby-head tests are failing with messages like:

> /home/runner/work/mechanize/mechanize/test/test_mechanize_cookie.rb:28:in 'block in TestMechanizeCookie#assert_cookie_parse': The call of Mechanize::Cookie./home/runner/work/mechanize/mechanize/lib/mechanize/cookie.rb:34:in 'Mechanize::CookieCMethods#parse needs to be fixed to follow the new API (HTTP::Cookie./home/runner/work/mechanize/mechanize/lib/mechanize/cookie.rb:34:in 'Mechanize::CookieCMethods#parse).

e.g. https://github.com/sparklemotion/mechanize/actions/runs/7927713758/job/21644607692#step:4:124

**Comment by flavorjones** [comment]
This got fixed at some point.
